# Generated by Django 3.0.7 on 2020-06-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletaeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpoint',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='addressComplement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='items',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='collectionpoint',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
