# Generated by Django 3.0.7 on 2020-06-28 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coletaeapi', '0002_auto_20200627_1903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollectionPoint',
            new_name='ORMCollectionPoint',
        ),
    ]
