# Generated by Django 3.0.7 on 2020-07-15 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coletaeapi', '0003_auto_20200628_2256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ORMCollectionPoint',
            new_name='CollectionPoint',
        ),
    ]
